-- =====================================================
-- Generated SQL Script for Instituciones Educativas
-- Extracted from: Lista-Directivos-QR (3).xlsx
-- Total records: 230
-- =====================================================

INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714055', '252', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679720', 'ALEJANDRO HERNANDEZ BONILLA', 'EBA-CEPTPRO', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0278937', '256', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275701', 'NUESTRA SEÑORA DEL CARMEN', 'SECUNDARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0752246', '403', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1425834', '22771 (p)', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608703', '22599 (p)', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0543058', '22573', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0291740', '22760 (p)', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0752261', 'JOHN F. KENNEDY', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0276048', 'ANDRES AVELINO CACERES (s)', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282012', '22250 (p)', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064575', '22759 (p)', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281816', '22230 ELADIO SARAVIA TASAYCO (P)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282285', '22277', 'PRIMARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1425156', '22766 LUIS LORENZO CANEPA PACHAS (s)', 'SECUNDARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679589', '22257 (s)', 'SECUNDARIA', 7, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1610963', '439', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1716398', '709', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062678', '407', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0543157', '22576 (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281931', '22242 JOAQUIN ORMEÑO CABRERA', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1731926', '22851', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1773746', '22268 (s)', 'SECUNDARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275875', 'CHINCHA (p)', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282061', '22255 ROLANDO ALZAMORA PAREDES (p)', 'PRIMARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0278929', '255 NIÑO JESUS DE PRAGA', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714113', '22655 (p)', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063841', 'JUAN VELASCO ALVARADO (p)', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0581165', 'MIGUEL GRAU SEMINARIO (s)', 'SECUNDARIA', 11, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714410', 'FE Y ALEGRIA 30 (s)', 'SECUNDARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1405323', 'SAN PEDRO (s)', 'SECUNDARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1610880', '436', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062769', '421', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281857', '22234 SANTIAGO CALLE SANTOS (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0468108', '22520', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679209', '240', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1678036', '704', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0563254', '22260 JOSE DE SAN MARTIN (i)', 'INICIAL-JARDIN', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1560606', '22237 AURELIO MOISES FLORES GONZALES (i)', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608976', 'PEDRO RONCEROS CALDERON (s)', 'SECUNDARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0292474', 'PARROQUIAL SAN JOSE (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630541', '235', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282277', '22276', 'PRIMARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1744747', '711', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282442', '23001 SEBASTIAN BARRANCA (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282335', '22282', 'PRIMARIA', 7, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0292516', '22531 (p)', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679597', '22258 SAN ANTONIO DE LISCAY (s)', 'SECUNDARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1408251', '22776', 'PRIMARIA', 7, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0278895', '243 ESPERANZA CARRILLO DE PESCHIERA', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0784736', '22679', 'PRIMARIA', 7, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608992', 'GREGORIO CONDE', 'EBA-CEPTPRO', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714170', '22659', 'PRIMARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281881', '22237 AURELIO MOISES FLORES GONZALES (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062876', '432', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281972', '22246', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281840', '22233 PAULINO REATEGUI AGUILAR (P)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0291849', '22758', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0291765', '22761', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('3002730', '22605 (s)', 'SECUNDARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0784744', '22678 (p)', 'PRIMARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282129', '22261 (p)', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1611003', '441', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275461', 'PROCERES DE LA INDEPENDENCIA (s)', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064120', 'TUPAC AMARU (s)', 'SECUNDARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1611508', '445', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1392760', '22234 SANTIAGO CALLE SANTOS (s)', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282434', '22492', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608968', '22613', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1752724', 'SINFONICA MODULO CHINCHA', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679605', '22259 APOSTOL SAN PEDRO (s)', 'SECUNDARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1695501', '440', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0276212', 'MANUEL CORPUS DE LA CRUZ', 'EBA-CEPTPRO', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1219542', '22754 (s)', 'SECUNDARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1731918', 'PRITE ANGELITOS DE JESUS', 'EBA-CEPTPRO', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281873', '22236 MAGDALENA BARBETTA AGUILAR (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062801', '22685 (i)', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1425784', '22770', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282152', '22264 (p)', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630608', '230', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0636753', '22627', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0752295', '22264 (i)', 'INICIAL-JARDIN', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0291823', '23516', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062710', '411', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1425305', 'RUBEN MARTINEZ PUICON', 'EBA-CEPTPRO', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062843', '429', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1755602', 'VIRGEN DE FATIMA', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282251', '22274', 'PRIMARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0564294', '22579 (p)', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063791', '22753', 'PRIMARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630699', '234', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630657', '233', 'INICIAL-JARDIN', 11, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630632', '232', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1425867', '435', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1678028', '703', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282137', '22262 SERGIO BAUTISTA QUISPE (p)', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630624', '231', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1678069', '707', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282293', '22278 (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275453', 'JOSE PARDO Y BARREDA (s)', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063130', '23001 SEBASTIAN BARRANCA (i)', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0292482', 'SANTA ROSA', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0564609', '22578', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0636837', '22636', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1357813', '22772 (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('3026424', '22779', 'PRIMARIA', 11, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063684', '22683', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0636662', '22628', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063775', '22752 (p)', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630566', '22228 (i)', 'INICIAL-JARDIN', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714212', '22662', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062728', '412', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679233', '245', 'INICIAL-JARDIN', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0278911', '254', 'INICIAL-JARDIN', 11, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0291955', '22756', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679399', '22645', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0509489', '223', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282350', '22284', 'PRIMARIA', 7, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1696814', 'SATELITE PRIMAVERAL', 'SECUNDARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1695519', '259 (p)', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1365774', 'JUAN PABLO FUENTES HUAMAN', 'EBA-CEPTPRO', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1631159', '22774 (s)', 'SECUNDARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0278945', '257', 'INICIAL-JARDIN', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282228', '22271', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1363340', '22773 (p)', 'PRIMARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1357839', '22281 (i)', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282327', '22281 (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1610898', '437', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062694', '410', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064179', 'SAN AGUSTIN (s)', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1678044', '705', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282236', '22272', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1457431', 'TONY GUBBELS', 'EBA-CEPTPRO', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0554527', '22528 (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275792', 'REINA DEL SANTISIMO ROSARIO (s)', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1678051', '706', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062686', '408', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0538298', '224', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064161', 'SAN ANTONIO (s)', 'SECUNDARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282418', '22290', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282004', '22249', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714006', '253', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0467928', '222', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063767', '22751', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0630574', '239', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679266', '248', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281980', '22247 JUAN XXIII', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063197', 'ANDRES AVELINO CACERES (i)', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063114', '448', 'INICIAL-JARDIN', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1378868', '22252 ANSELMO ABAD DE LA CRUZ (i)', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063007', '447', 'INICIAL-JARDIN', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282046', '22253 (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0291831', '22757 (p)', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0868166', '22685 (p)', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1219666', 'SANTA CECILIA (p)', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('3046596', '22803 SEÑOR DE LOS MILAGROS', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0528471', '22565', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282178', '22266 (p)', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1388941', '22240 FRANCISCO CORBETTO ROCCA (i)', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1678010', '702', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275933', 'SANTA ANA', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1695485', '306 (p)', 'PRIMARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281949', '22243 (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714147', '22657 (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064112', '22286 SAN VICENTE DE PAUL (s)', 'SECUNDARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608307', 'PEDRO RONCEROS CALDERON (t)', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0528778', '22564', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1657857', '701', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063734', '22687 ALMIRANTE MIGUEL GRAU (p)', 'PRIMARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282079', '22256 SAN ANTONIO DE PADUA (p)', 'PRIMARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282319', '22280 (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275537', 'CHINCHAYSUYO (s)', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0564302', '22580', 'PRIMARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0752311', '22665', 'PRIMARIA', 7, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062850', '431', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282186', '22267', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1425891', '22247', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282301', '22279', 'PRIMARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1744754', '712', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679217', '241', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282400', '22289', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1357805', '22772 (i)', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0278903', '244', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0276089', 'JOHN F. KENNEDY', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608240', '22230 ELADIO SARAVIA TASAYCO (I)', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608265', '22603', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064195', 'DOS DE MAYO (s)', 'SECUNDARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0713990', '249', 'INICIAL-JARDIN', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064153', 'JOSE YATACO PACHAS (s)', 'SECUNDARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0608950', '22598', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714097', '22654 (p)', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0538595', '225 EMILIA BARCIA BONIFFATTI', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281915', '22240 FRANCISCO CORBETTO ROCCA (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679654', 'HORACIO ZEBALLOS GAMEZ (s)', 'SECUNDARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282384', '22287', 'PRIMARIA', 8, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282426', '22480 JOSE CARLOS MARIATEGUI (p)', 'PRIMARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0468090', '22519 (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0553909', 'CIRO ALEGRIA', 'SECUNDARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275677', '9 DE DICIEMBRE', 'SECUNDARIA', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282160', '22265 (p)', 'PRIMARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679258', '247', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282269', '22275', 'PRIMARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275693', 'SIMON BOLIVAR', 'SECUNDARIA', 4, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1716380', '708', 'INICIAL-JARDIN', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062637', '404', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1610922', '438', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281907', 'ANDRES AVELINO CACERES (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1062736', '417', 'INICIAL-JARDIN', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281774', '22226 NUESTRA SEÑORA DE FATIMA', 'PRIMARIA', 3, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1664531', '22752 (i)', 'INICIAL-JARDIN', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714030', '251', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1254978', 'SANTA TERESITA DEL NIÑO JESUS (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1063049', '22480 JOSE CARLOS MARIATEGUI (i)', 'INICIAL-JARDIN', 2, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1744739', '710', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0636696', '22635', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275685', 'MELCHORITA SARAVIA (s)', 'SECUNDARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1064203', 'ABRAHAM VALDELOMAR PINTO (s)', 'SECUNDARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282038', '22252 ANSELMO ABAD DE LA CRUZ (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0278952', '221', 'INICIAL-JARDIN', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1359488', 'ANDRES AVELINO CACERES', 'EBA-CEPTPRO', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0553800', 'JUAN C. DE MORA', 'SECUNDARIA', 10, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0714154', '22658', 'PRIMARIA', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('1611078', '442', 'INICIAL-JARDIN', 6, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0752238', '260', 'INICIAL-JARDIN', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0281899', '22238 SAN MARTIN DE PORRES (p)', 'PRIMARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0275529', 'SANTA ANA', 'SECUNDARIA', 5, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0282053', '22254 (p)', 'PRIMARIA', 1, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0679613', '22273 (s)', 'SECUNDARIA', 9, true);
INSERT INTO instituciones_educativas (codigoModular, nombreIE, nivelModalidad, distritoId, estado) VALUES ('0752345', '22283 (s)', 'SECUNDARIA', 7, true);